### ISSUE TITLE
.svg might be a problem on IE10

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#104]
From @MatthewVita 
: (

we might have to fix these with a polyfill, etc.?

Or we could just blame the user on this and let them deal?

**Comment by timothyfcook** [comment]
It doesn't break functionality, so... ?

**Comment by MatthewVita** [comment]
I actually tested this on IE10 and IE11, but I'm sure it happens on IE9.

@timothyfcook we can't blame the user b/c IE10 and IE11 are modern browsers. Plus, we have to support IE9 per Cameron's point about a bunch of schools/libraries still using it.

@cameronscott137 the issue is with positioning of our main logo in the top left corner (it drops down like ~70px) and the search icon looks really weird.

...in the spirit of MVP, we're not breaking functionality so I would say this is low priority C:

**Comment by cameronscott137** [comment]
@timothyfcook @MatthewVita Yeah, we will need to write a bit of extra styling for SVG displays on IE9. Check out http://caniuse.com/#search=svg, specifically the second footnote.

Should display totally fine in IE10 and IE11—can you elaborate?

**Comment by MatthewVita** [comment]
@cameronscott137 

Just tested on IE11 (doesn't break functionality, but looks off):

![1](https://cloud.githubusercontent.com/assets/1715206/8492641/c0f3d38c-211a-11e5-939b-24ae65afd82a.PNG)

I can downgrade to IE10 and IE9 to test there as well... just LMK.

**Comment by MatthewVita** [comment]
where do we stand on this?

**Comment by timothyfcook** [comment]
I'm not worried about this, .svg is the way to go here. I'm a fan of building for the future. We can regress later if need be.

**Comment by MatthewVita** [comment]
we _will_ have to regress later since we have an IE9+ requirement since some schools/libraries use it. For the MVP, this is not a big deal IMO
