### ISSUE TITLE
Opportunity Instance Endpoints Discussion

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#108]
@justinxreese I'd like to follow up with our short discussion about the Explore Cards/Explore Topics search endpoints:

right now for Explore opportunity instances-related GETs, we have:

``` code
/opportunity_instances.json
/opportunity_instances/n.json
/opportunity_instances/topic/n.json
[0]
[1]
```

right now (with the silly test data server whose main endpoint for this is incorrectly `/api/v1/opportunities/topic/:topic`, because it's just a dummy data server), users can 
search for opportunity instances via the search in the navbar (which directs to Explore page) via entering either a general topic name or a opportunity instance name and when on the Explore page, clicking on a "Topic Chip" will hit that same endpoint.

You mentioned that we should separate these to two endpoints, so I'd like more info on if we can/should do that. I'm thinking it may be best to have the following and call it a day, since we don't know if the user is searching with a topic or an opportunity:

``` code
/api/v1/opportunity_instances/search/:term
```

...or with your convention:

``` code
/opportunity_instances/search/term.json
```

where `term` is either a topic or an opportunity inst. name.

Also, we'll still keep the `/opportunity_instances/n.json` for the individual opportunities pages, I'm just thinking that we may want to rename the `/opportunity_instances/topic/n.json` route

[0] I'm leaving out the `topic` endpoint because my understanding is that the consumers will define those in their client configs (at least for the MVP). https://github.com/saxifrage/CaaC_Explore/blob/master/app/shared/conf/ConfService.js#L11-L23 (@timothyfcook , can you confirm?)

[1] I'm leaving out the `opportunities` endpoint because it won't be hit on Explore page, of course

**Comment by justinxreese** [comment]
We DO know if the user is searching a topic or an opportunity based on which part of the interface they are using: the chips or the search field. We can include topics in searches from the search field but should be accessed differently so that they can be separated in the UI.

With your suggested setup, opportunities with a topic name in their title will appear within a topic regardless if the word is relevant to the opportunity's topic. "Django PGH: Django Rest Framework" would appear under the "Rest" topic. "Callback-free Concurrency: Elixir vs Node.js" would appear under the "Free" topic, even if it cost $10. "#StarterSeries: Tools of the Trade" would appear under the "Tools" topic, even if that topic is meant for physical tools rather than software. Those are just examples from Code & Supply over the last 1 month. I'm sure other organizations will also have misleading titles and descriptions.

I am 100% sure they should not be combined.

The API endpoints should be:

```
/api/v1/opportunity_instances.json - List all opportunity instances
/api/v1/opportunity_instances/1.json - Get a single opportunity instance
/api/v1/opportunity_instances/search/:term.json - List all opportunity instances matching a search term
/api/v1/opportunity_instances/topic/:topic.json - List all opportunity instances from a given topic
/api/v1/topics.json - List all topics
/api/v1/topics/1.json - List a single topic
```

Topic configuration should be done at the Rails level as it is data. You're mixing business logic into the view layer. The view layer should be agnostic and take any list of topics from the server. Same with application name and city.

**Comment by MatthewVita** [comment]
I definately see your logic and appreciate the breakdown, but I think @timothyfcook asked for the search to work by topic or opportunity. I'm sure he'll follow up with us soon :+1: 

Topic configuration should be stored in the backend, I agree. However, my understanding is that it will sit at the client level for the MVP because we aren't going to build a feature that allows for admins to CRUD topics quite yet. Application name and city can live on the client for now and since the idea is for cities to fork our codebase, I don't see those as a huge deal, TBH.

**Comment by justinxreese** [comment]
@timothyfcook's feature is not lost with my suggested architecture. We will include category in the full text search used by `/search/:term.json`

**Comment by MatthewVita** [comment]
Awesome. Very productive discussion.

1 more question and we'll just leave the closing of this discussion to Tim:

Based on my last post, can you comment on if there was a formal decision to add an MVP admin feature for the CRUD'ing topics? If so, I'd love to get those topics out of the frontend conf. If not, let's respect the current scope and I'll add an issue the the bottom of our backlog.

**Comment by justinxreese** [comment]
@MatthewVita even without any admin CRUD, the rails application can load them similarly how they are loaded by the JS in a config file. But I do think, regardless of the admin interface, it is important to serve them through the API early on in our development.

**Comment by MatthewVita** [comment]
works for me! I can commit to that next sprint.

**Comment by MatthewVita** [comment]
https://github.com/saxifrage/learn/issues/109

**Comment by timothyfcook** [comment]
Thanks for hashing this out. Yeah, goal for me is:
1. Topic buttons filter by topics.
2. Search form filters based on input and references 
   ....
   I'm also thinking these might make sense:
3. `organizer.name`
4. `description`

might be good to include. In case the `topic` is `coding` and the title of the talk is `Learning MVC` but the description mentions that the MVC talk will use Ruby on Rails.

A search for "Ruby on Rails" would not pull up the MVC talk unless description was searched.

I'm not as sure about `organizer.name` since you could (eventually) go to the `organizer` page and see all of the events associated with them. But, if you search "code" it might make sense for all "Code & Supply" events to come up in the results, no?

Just don't search "supply"...?

**Comment by timothyfcook** [comment]
This discussion is making me realize how a `tags` array might make sense .... basically just an array that organizers can fill up with relevant search terms and we could use that instead of `description` ...I just don't think that `opportunity.name` and `topic` will always be enough for the results to match the intended will of the searcher.

This, of course, is why an awesome visual browsing tree is going to be the KILLER APP of v 3.0...

**Comment by justinxreese** [comment]
I think we should definitely add tags later (much later, totally a “very
cool to have”). I have a cool vision of how they’d work as auto-complete
search terms that can be added to a query.

I think the search should include topic. It’s okay to cross-polinate in
that direction, just not in the other direction (looking for a topic).
Organizer name could be included, but we can actually toggle the relevancy
it has to the search.

**Comment by justinxreese** [comment]
That last bit was an incomplete thought. I think organizer name could be misleading, but we can easily toggle organizer name's relevancy in searches so that it shows up later in search results.

**Comment by MatthewVita** [comment]
okay, so if I'm following this correctly a navbar -> explore page search term will go against:
- opportunity inst name
- opportunity inst description
- opportunity inst topic

...with searches being %wildcard-and-to-lowercase%, ofc

right?

**Comment by justinxreese** [comment]
Basically those fields. We can add and remove fields as we see fit and also boost certain fields over others so they're deemed more relevant.

Just send me exactly what the user types. The search library will take care of formatting it and optimizing the results.

**Comment by MatthewVita** [comment]
k
