### ISSUE TITLE
Create sketch of Admin account page

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#136]

**Comment by cameronscott137** [comment]
To ensure we don't miss any functionality, we've built up a set of user stories that we will be using to inform the admin design. These are based predominantly on the work that's been done on the data model thus far, as well as a few CMS best practices.

For ease of conversation, we've split in-person and digital events into separate stories, though the goal is to encompass both as a single form.

Would love any feedback or revisions here. Otherwise, should have screens tomorrow to discuss.

**As a user, I can add and manage an in-person event:**
1. I can add an event name (required).
2. I can add an event date, start time, and end time.
3. I can specify whether the event is reoccurring.
   - If reoccurring, I can specify at what interval the event occurs.
   - If reoccurring, I can specify different venue per event.
4. I can add an event venue name (required)
5. I can add an event venue neighborhood
6. I can add an event venue address (required).
7. I can add an registration link (required.)
8. I can add an external website (if different from organization website).
9. I can add a short description.
10. I can add a longer event description.
11. I can add an opportunity format
    - Apprenticeship/internship
    - Conference
    - Course
    - Exhibition (art, etc.)
    - Learning Community
    - Lecture
    - Meetup
    - Mentor Relationship
    - Volunteer Experience
    - Workshop
    - Other
12. I can add a registration deadline.
13. I can add an age range.
14. I can add an event cost.
15. I can specify a point of contact (if different from event creator).
16. I can add a proportionally square event icon.
17. I can add a banner event image.
18. I can specify relevant badges that pertain to the event topic.
19. I can determine whether this is event is listed, or is in “draft.”

**As a user, I can add and manage an online event:**
1. I can add an event name (required.)
2. I can add an event date, start time, and end time.
3. I can specify whether the event is reoccurring.
   - If reoccurring, I can specify at what interval the event occurs.
   - If reoccurring, I can specify a different URL per event (eg. Hangout, WebEx, etc.)
4. I can add a registration URL
5. I can add a registration deadline
6. I can add an opportunity format
   - Apprenticeship/internship
   - Conference
   - Course
   - Exhibition (art, etc.)
   - Learning Community
   - Lecture
   - Meetup
   - Mentor Relationship
   - Volunteer Experience
   - Workshop
   - Other
7. I can add an age range.
8. I can add an event cost.
9. I can specify a point of contact (if different from event creator).
   - Name
   - Email
   - Telephone
10. I can add a proportionally square event icon.
11. I can add a banner event image.
12. I can specify relevant badges that pertain to the event topic.
13. I can determine whether this is event is listed, or is in “draft.”
14. I can specify a listing start time, and a listing end time.

**As a user, I can add and manage an organization:**
1. I can add organization name.
2. I can add an organization URL.
3. I can add organization description.
4. I can an organization point of contact.
    - Name
    - Email
    - Telephone
5. I can add a proportionally square organization icon.
6. I can add a organization banner image.

**As a user, I can add and manage my personal profile:**
1. I can add my name.
2. I can add my email address (and whether or not it is publicly shown).
3. I can reset my password.
4. I can add and manage my system email preferences.

**Comment by timothyfcook** [comment]
This should be combined with #198
