### ISSUE TITLE
Curation

### ISSUE THREAD

**Issue by Arf375** [saxifrage/learn#150]
# Curation Process

The following steps are to be performed by the Anchor Advisory Panel and optional crowd-sourcing.
#0. End-user Pages
- A page on our platform to submit an opportunity instance request. (Must allow user to detail their instance and easily "tag" competencies [0])
- A page on our platform for the community to request particular classes
#1. Identify
- Identify local learning opportunity instances already available
- Identify qualified organizations that would possibly sponsor new learning instances
- Assign person to continually check community "class requests" email account and determine if an organization could sponsor such an opportunity instance
#2. Gather
- Email/Tweet the organizers of existing local learning opportunity instances a link to our platform to enter their opportunity instance
- Email qualified organizations that would possibly sponsor new learning instances a description of our platform and how sponsoring would be mutually beneficial. Include a link to our platform to enter their opportunity instance and a phone number of a volunteer from the Anchor Advisory Panel.
#3. Review

Reviews inbound local learning opportunity instance requests (via manual consumption of existing opportunities and by virtue of marketing) on the admin dashboard.

Checklist:
- [ ] Credibility of instructor (one-time, informal background check)
- [ ] Credibility of sponsor(s) (one-time)
- [ ] If opportunity instance location is safe
- [ ] If opportunity competencies are relevant

...if criteria is met, add the opportunity instance. Else, reach out to submitting organization.

[0] will not apply to our MVP, but these tags will help when we have a universal badge API to support competencies and an associated scale. Matthew/Addison working on a mockup in the universal badge api repository

**Comment by MatthewVita** [comment]
:hamburger:

**Comment by timothyfcook** [comment]
@Arf375 thanks for the work so far!

Some thoughts:
- I like the idea of the public being able to request classes. Once we get to that point, we could setup a City-level admin account that could have a queue of these requests. They shouldn't be sent to e-mail.
- Definitely a lot of outstanding questions on the "Review" work:
  - How do we gauge/decide credibility? Is this feasible and necessary? Could we possibly just require instructors to provide supporting evidence regarding their credibility and let the public decide? Kind of like Kickstarter, etc.
  - What is a "sponsor" in this context?
  - How do we gauge the safeness of a location? I think this might be outside of the scope.
  - It might be too difficult to gauge the relevance of competencies. This would be up to the instructor.

In general, we need to think more and more about how we can use public review systems, transparent profiles, and a high-bar to entry in order to ensure quality. We can't get into any process that is too onerous. Scalability is huge here.

Note: Eventually, it might be possible to do some identity verification.

**Comment by MatthewVita** [comment]
2 cents: I was originally on board with the "safeness of location" checkbox, but I'd like to think that organizers entering requests are intelligent and reasonable people. Also, we don't want the anchor taking any liability, so it's on the organizer.

**Comment by MatthewVita** [comment]
Okay @Arf375  and @timothyfcook, I set up a "Getting Started" guide that overviews objective, curation, and guidelines here: https://github.com/saxifrage/learn/commit/33e93d053f913f9fdc80a5e9875cea35fe2ca63f

It is linked from our website's home page and our repo's README.md.

Please let me know if your have any comments on it. Otherwise, we can close the issue.

**Comment by MatthewVita** [comment]
(Tim, I addressed some of your bullets points concisely in that doc)

**Comment by timothyfcook** [comment]
Closing! We can revisit this closer to a public launch, maybe after we get feedback from real users.

**Comment by MatthewVita** [comment]
awesome
