### ISSUE TITLE
Caac Guidelines

### ISSUE THREAD

**Issue by Arf375** [saxifrage/learn#151]
# CaaC Guidelines

Put together document that will be committed into the codebase that each "Anchor" city should follow.

Outline the following
- Objective of the app
- Roles of the Anchor Advisory Panel
- Scope of crowd-sourcing efforts
- Brand guidelines

**Comment by MatthewVita** [comment]
@timothyfcook Addison and I put this together... trying to list out the high-level pieces before a draft is created.

Thoughts?

**Comment by timothyfcook** [comment]
Look good so far. What is "Scope of crowd-sourcing efforts" ?

**Comment by MatthewVita** [comment]
Maybe we should remove it. The original thought was that the panel could leverage crowdsourcing to maximize learning opportunities, but that doesn't align with the quality-driven curation process.

**Comment by timothyfcook** [comment]
No, yeah we definitely want the whole community listing opportunities. We will just also need to use the crowd to curate them as they come in.

Having good quantity is super important.

**Comment by MatthewVita** [comment]
I see, but wouldn't it make more sense for the community to contribute opportunities and _anchor_ to curate them as they come in?

**Comment by timothyfcook** [comment]
I think it can be some of both. I imagine the anchor could curate initially, but the scale would get so great that the anchor would need to empower community curators to manage different sections.

**Comment by MatthewVita** [comment]
If I'm following you, natural "partnerships" would arise over time between the Anchor and other parties.

For example, the "Anchor" may be Sprout Fund (which does most of the curation), but people like Justin of Code & Supply can jump in to tackle software-related curation because he's an expert. Although he's not a part of the formal Anchor, he's recognized by the Anchor as an "expert community member".

We don't have to have a formal process for things like this (or in general for the guidelines [0]). I feel as though copy/pasting the example above would be satisfactory.

[0] The _only_ thing that needs to be formal is the idea of the Anchor Advisory Panel.

agree?

**Comment by MatthewVita** [comment]
If we're okay with these high level points, I will work with Addison to put together v1 of the document. Will need  3 votes in order to move forward with it, however.
- [x] Myself
- [x] @Arf375 
- [x] @timothyfcook

**Comment by timothyfcook** [comment]
Re-partnerships and expert curators comment: Exactly!

**Comment by MatthewVita** [comment]
@Arf375 ? :)

**Comment by MatthewVita** [comment]
Okay @Arf375  and @timothyfcook, I set up a "Getting Started" guide that overviews objective, curation, and guidelines here: https://github.com/saxifrage/learn/commit/33e93d053f913f9fdc80a5e9875cea35fe2ca63f

It is linked from our website's home page and our repo's README.md.

Please let me know if your have any comments on it. Otherwise, we can close the issue.

**Comment by timothyfcook** [comment]
Looks like a good start!
