### ISSUE TITLE
Create beautiful homepage design

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#186]
so they find something beautiful on the home page that explains the epic vision of this project.

**Comment by cameronscott137** [comment]
@chelseaerdner and I will roll on this, looking to @timothyfcook as content authority.

**Comment by timothyfcook** [comment]
I'm thinking something like "We are all schoolmasters, and our schoolhouse is the universe."

**Comment by timothyfcook** [comment]
This is a homepage for learnpgh.org (check out the old mock-up for reference: http://learnpgh.org/)

I like the idea of:
- a full-page photo of pittsburgh (with the CaaC monomark in the corner)
- a brief description of what exists now (resource discovery, maps), with a few bullet points about the dream platform we are building towards (badges, lifelong learning archives)
- a search bar (takes you to the CaaC directory page) and an EXPLORE button (takes you to the map)
- the Thoreau quote: "We are all schoolmasters, and our schoolhouse is the universe."

Will work on a wireframe soon.

**Comment by MatthewVita** [comment]
@timothyfcook I was thinking we'd build on the "home" page that we currently have because we'd have the same navbar and look+feel all in one place. Thoughts?

**Comment by timothyfcook** [comment]
what "home" page? the one at http://cityasacampus.org/ ?

My thinking was that site is for the open-source software project, but we would build a homepage for learn.pgh which is an instance of the platform being used in a real place.

**Comment by MatthewVita** [comment]
the one in this repo.

**Comment by timothyfcook** [comment]
gotcha. Yeah we could use the existing nav bar, I'll consider that when doing some wire frames.

**Comment by MatthewVita** [comment]
Cool. And I'm not just talking about "using the existing nav bar", I mean we'd literally use that page as the home page.

It's here: https://github.com/saxifrage/cityasacampus/tree/master/client/app/home

**Comment by MatthewVita** [comment]
it's a very exciting page at the moment xD

**Comment by cameronscott137** [comment]
@chelseaerdner and I are reviewing now. All feedback so far makes sense: we're building a home page for a specific instance of the platform—in this case, learnpgh.org. We'll see the same nav and footer, and obviously lean heavily on established style rules.

@timothyfcook, would dig any wireframes and additional language as you have them. Otherwise, Chelsea's diving in and will have a draft out for review early next week.

**Comment by timothyfcook** [comment]
Some thoughts: 
![img_0339](https://cloud.githubusercontent.com/assets/1823300/9996625/d4eca394-6055-11e5-9723-fc60ee95a37d.JPG)

**Comment by chelseaerdner** [comment]
Perfect timing @timothyfcook, actually working on this now.

**Comment by timothyfcook** [comment]
Nice! Don't forget our existing page layout:  
![screen shot 2015-09-21 at 11 59 29 am](https://cloud.githubusercontent.com/assets/1823300/9997086/46f46a7e-6058-11e5-8551-9e23ce8d81a1.png)

**Comment by chelseaerdner** [comment]
@timothyfcook here is the first draft of the homepage layout. There is lorem ipsum placeholder text in many places but I figured as we work out layout, we can write to it. 

In your notes, you mentioned a large pittsburgh inspired background image but because we have invested so much time into making this awesome resource map, I'd really like to play up that concept on the homepage. I attached a gif under the layout just to give you an idea of a quick idea I was thinking for the hero image. At the end of the day, I think it would be more interesting to record someone navigation the resource in a short video format rather than just an easy gif. 

Let me know your thoughts!

![caac_homepage_09212015-01](https://cloud.githubusercontent.com/assets/11842603/10005329/a47c0c02-6084-11e5-9cc7-3b426a80276a.png)

![caac_homepage_gif](https://cloud.githubusercontent.com/assets/11842603/10005331/a7db57f4-6084-11e5-965d-9c84d87ba508.gif)

**Comment by timothyfcook** [comment]
This is great. I like the .gif with the changes blocks, let's use that as the background.

Also, the homepage will actually get stood up as "LearnPgh", our local use case for the City as a Campus platform.

I'll write some copy for the bullets.

**Comment by timothyfcook** [comment]
I'd say @cameronscott137 can go ahead and build up the homepage based on this.

One step closer to actually publishing this thing on the internets!

**Comment by cameronscott137** [comment]
@timothyfcook That's a big 10-4.

**Comment by timothyfcook** [comment]
@cameronscott137 let's get this homepage up asap

**Comment by timothyfcook** [comment]
Since we have the Design finished, I'll close this and stand up a new implementation ticket.
