### ISSUE TITLE
Dashboard Add Opportunity Instance (Organizer Context)

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#198]
USER STORY:
As an authenticated organizer, I wish to add an opportunity instance

ACCEPTANCE CRITERIA:
- form:
  - Name (not null)
  - Address (not null)
  - Description (not null)
  - Registration URL (not null)
  - Location name (not null)
  - Registration deadline (not null)
    - use datetime picker
  - Logo url  (not null)
  - Starts at (not null)
    - use datetime picker
  - Zipcode (not null)
  - IsOnline (nullable)
  - Price (nullable)
  - Min/Max Age (nullable)
    - use dropdowns
- Uses nav/theme from “regular” site

**Comment by timothyfcook** [comment]
Let's separate it out so that they first create an `opportunity` and then schedule `opportunity_instance` objects related to it. This could all be part of the same form on the same page. Maybe just broken up a bit with a "+" button to add/schedule instances related to the `opportunity` 

Also:
- IsOnline should be inputted alongside the Location information. There should be some conditional form logic:
- IF IsOnline = True, then user inputs information for online opportunity properties (e.g. URL
- ELSE user inputs information for local opportunity properties

In other thoughts:
- maybe it would be useful for clarity in the data-model to call the `opportunity` property `opportunity_class` instead?
- I'm also considering a tweak to the data model in which `LocalOpportunityDetails` and `OnlineOpportunityDetails` are split out into separate objects nested within the `opportunity_instance` 

also: are we camelCasing or snake_casing ? I was using `snake_case` in my .json sketch originally, but not sure how Justin implemented it

**Comment by timothyfcook** [comment]
We can also reference what @cameronscott137 and I sketched out in #136

**Comment by dmtroyer** [comment]
Going to dive into this using the `organizer_users` work done in #251

**Comment by dmtroyer** [comment]
Note: We should consider a broad authorization strategy.

e.g. A user should not be able to edit an opportunity for which they are not a user for the opportunity's organizer.

I dug around devise for a bit, but it doesn't seem to include much in the way of internal authorization. There are some gems out there like cancan, but this might be overkill.

**Comment by timothyfcook** [comment]
Cool, just FYI there was an issue open just for scoping `opportunity` to a unique `organizer` __> #187

**Comment by MatthewVita** [comment]
I just added that to this Epic

**Comment by dmtroyer** [comment]
Hey guys ( @timothyfcook @MatthewVita ),

I'm seeing a lack of reference in this user story to some fields currently in the `opportunity` and `opportunity_instance` models.
- `program_type`
  - I assume this will be superseded by `resource_type` and `reosource_sub_type`, in which case it could probably be deleted from the model entirely? see https://github.com/saxifrage/cityasacampus/issues/163#issuecomment-145126223
- `hide` and `hide_reason`
  - I assume these should stay in
- `contact_name`, `contact_email`, `contact_phone`
  - Again, I assume these should stay in

Don't mean to get too caught up in the particulars, it was just a very particular list up top so I wanted to run this by somebody.

**Comment by dmtroyer** [comment]
Also, `extra_data` is not referenced in the US.

**Comment by dmtroyer** [comment]
A separate question for @MatthewVita: do you have a favorite datetime picker strategy? Some that I found:
- [HTML5 datetime](http://www.w3schools.com/html/html_form_input_types.asp)
  - Currently not supported by any browsers
- [daterangepicker](http://www.daterangepicker.com/#ex2)
  - dependent on bootstrap
- [bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker)
  - I think this one is gemified somewhere.

Anyhow, this doesn't seem super high priority to me, just thought I would throw this out there before I move along.

**Comment by MatthewVita** [comment]
@dmtroyer
- I missed those fields, please add them to the US
- datetime strategy tends to be a library with the single responsibility of datetime picking/custom themes. I tend to dislike bringing in dependencies (other than jQuery and Momentjs, of course) when using a datetime component. I've used this with success in the past. jQuery/Moment example: http://xdsoft.net/jqplugins/datetimepicker/

``` javascript
jQuery('#my-awesome-date-time-id').datetimepicker({
  format:'DD.MM.YYYY h:mm a',
  formatTime:'h:mm a',
  formatDate:'DD.MM.YYYY'
});
```

thoughts?

**Comment by dmtroyer** [comment]
@MatthewVita thanks for the recommendation!

I got the xdsoft datetimepicker to work with moment.js. However, I spun my wheels a bit on a strategy for transforming `DateTime` fields so that what is displayed to the user is friendlier and more readable than what Rails gives by default.

Because of this, for the time being, I went with [DatetimeLocal HTML5 inputs](http://www.w3schools.com/jsref/dom_obj_datetime-local.asp) which gives a barebones datetime picker in chrome. We could revisit this if you have thoughts as to how to make the xdsoft datetimepicker play more nicely with Rails. Sorry, I should have taken some screenshots before I stripped the xdsoft datetimepicker back out.

**Comment by MatthewVita** [comment]
@dmtroyer this will work for the demo but we have a IE9 dependency :(

**Comment by dmtroyer** [comment]
OK, I'll create an issue to update the datetime picker.

**Comment by dmtroyer** [comment]
Broke out the datetime picker issue to #274

**Comment by timothyfcook** [comment]
Nice!
