### ISSUE TITLE
Move Tooltip

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#281]
It's awkward to have the tooltip occupy the same space as the mouse cursor: lower right of the thing I'm pointing to. I suggest moving the tooltip to top center.

**Comment by timothyfcook** [comment]
@cameronscott137 this is one of the most annoying UI issues

**Comment by cameronscott137** [comment]
@timothyfcook Fixed, mostly. The bummer here is that we need the height of the tooltip in order to position it correctly. What happens is:
1. User hovers over node.
2. Height of tooltip is calculated.
3. Position of tooltip is calculated using that height.
4. Tooltip is displayed.

This means that most tooltips work, but for tooltips that extend to two lines, there the position of the tooltip jumps slightly.

Tell me if this is good for the demo. To get it outta the way of the cursor, we can also position lower left.

**Comment by chadwhitacre** [comment]
@timothyfcook You want this on the left now, yes?

**Comment by timothyfcook** [comment]
Probably. Iterate! Center ain't great

**Comment by chadwhitacre** [comment]
Moved in #328.
