### ISSUE TITLE
Single- Or Multi-Tenant?

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#285]
We should make a thoughtful decision soon about whether we are building a single-tenant or [multi-tenant](https://en.wikipedia.org/wiki/Multitenancy) application.

**Comment by MatthewVita** [comment]
We've talked about it being single tenant because each city will fork the repo and stand up their own instance.

**Comment by timothyfcook** [comment]
Yeah, we talked more today IRL about the benefits of multi-tenant. We can discuss more on this once we have mvp up and running.

**Comment by MatthewVita** [comment]
I'd love to be involved with these discussion. If you can, please record them if I'm at work. I've been thinking about the various ways we could go about this.

awesome!

**Comment by dmtroyer** [comment]
Maybe we could schedule a dinner meeting or something IRL where we can discuss larger architecture post mvp issues such as this? Or we can flush things out on a issue by issue basis.

**Comment by MatthewVita** [comment]
I'm stupidly busy this week. Is there any weekday _next_ week that would work for you all?

**Comment by timothyfcook** [comment]
Next week sounds fun. Maybe we can convince @whit537 to stay for dinner on Monday after work?

**Comment by chadwhitacre** [comment]
I'd definitely be up for that. It would be great for team-building to have a celebration and pow-wow. Besides, @MatthewVita and I have yet to meet face-to-face! :-)

**Comment by MatthewVita** [comment]
thanks for setting this up, Tim (https://github.com/saxifrage/cityasacampus/issues/305)

@whit537 looking forward to meeting with you in person as well!

![img](https://media.giphy.com/media/a74pSGN7wvT7a/giphy.gif)

**Comment by MatthewVita** [comment]
@whit537, @timothyfcook, @dmtroyer:

Okay, so since I failed to make it to the IRL meeting let's try and discuss this here. Else, I'm free for a ghangout on Sunday at any time.

Let's list out pros/cons of multitenant:

Pros:
- We would be a true SaaS
- CaaC branding would be prominent
- Nation-wide scaling isn't all that hard with AWS images/load balancers
- It's easier on each city since they aren't responsible for self hosting
- updating all cities is easy since everything is centralized

Cons:
- Can get kind of expensive when CaaC takes off and we are responsible for keeping the lights on (in terms of AWS traffic and servers)
- We'd have to rethink a lot of technical decisions/refactor a lot of stuff in order to support this
- We'd have to consider that different cities are going to want to style their city site in a certain way
- We'd have to reassess our roadmap (http://cityasacampus.org/doc/roadmap.html) to include a decent scope of work to get this up and running

My vote? I think we should _definitely_ plan for multi tenancy but I don't think it's an urgent need as compared to things like finishing off the MVP and finishing the deployment epic.

**Comment by timothyfcook** [comment]
Pros:
- Easier to ensure quality and security across all instances

Cons:
- Extra time cost upfront

I'm 100% in agreement with @MatthewVita ...let's plan for multi-tenancy, but not work on it too much right now. Number one goal is to finish the MVP so that we can get real admin users on the platform adding and publishing opportunities.

User feedback will help us level-up our game and test our assumptions and having a real MVP will, hopefully, enable us to leverage our work for future funding.

All hands on the Admin UI!
