### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by MatthewVita** [saxifrage/learn#36]
I do like the name "City as Campus"... but I'm wondering if we should really stick an "a" in there making it "City as a Campus".

In the tech world, we have "Platform as a Service" (PaaS) and "Software as a Service" (SaaS) to name a couple. Not only is the "as a" grammatically correct, it helps convey meaning.

...Thoughts?

**Comment by justinxreese** [comment]
:+1:

**Comment by cameronscott137** [comment]
[image: :+1:]

On Sun, Mar 22, 2015 at 7:06 PM, Justin Reese notifications@github.com
wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/learn/issues/36#issuecomment-84729794.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Yeah, I'll do some thinking on this. They are both grammatically correct, but I'm with you... 

...another name entirely might make sense as well. I'll consider.

**Comment by MatthewVita** [comment]
I wasn't implying it was grammatically incorrect, but I can see why my post may have came off that way.

I'll leave you to think on this and then we can hold a vote.

**Comment by timothyfcook** [comment]
sounds good! thinking hard. Part of it was that we just needed somewhere to park things and I owned that domain.

**Comment by timothyfcook** [comment]
names with available domains:
0. City as Campus -- cityascampus.org
1. City as a Campus -- cityasacampus.org
2. Fractal Schools  -- fractalschools.org
3. Fractal Learning -- fractallearning.org
4. Fractal Campus -- fractalcampus.org
5. Map of Learning -- mapoflearning.org
6. Graph of Learning -- graphoflearning.org
7. Knowledge Framework -- knowledgeframework.org
8. Structure of Learning -- structureoflearning.org

**Comment by MatthewVita** [comment]
I still like 1 and kind of like 2. I feel like we should have the word "campus", "school", "education", or "learning" right in the name so it's immediately understandable.

How about:
0 http://openschools.io/
1 http://openlearning.space/
2 http://opencampus.io/

**Comment by timothyfcook** [comment]
@matthannigan any thoughts here? We want to pick out a generic name for our white-label tool aside from "Learn.Pgh", etc. so that we can give it a home that isn't location specific. Mostly just using it as a name for the repository and the domain for the site where we host documentation, etc.

I'm leaning more towards @MatthewVita 's "City as a Campus" preference, I like the SaaS reference. Although it is really similar to the program at Winchester Thurston (City as Your Campus)... though that's not necessarily a negative and they have zero web presence for that name.

.io is so hot these days...

**Comment by matthannigan** [comment]
@timothyfcook I suggest just choosing a disposable product codename for the time being. Perhaps using something like http://nomaine.com/en/ to find an available, pronounceable thing.

**Comment by timothyfcook** [comment]
since most everyone :+1: voted it and I already got the DNS switched, let's just roll with CityasaCampus (CaaC). I like the SaaS reference a lot and it's already setup. Per Matt's note, name isn't very important right now, I just got a little carried away geeking out on available domains last night (as I often do).

We're up and running now at http://cityasacampus.org/ now we just need to make it not ugly and put things there per #24 .
