### ISSUE TITLE
Design and Implement Layout for Explore Page

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#51]
Reference: http://national.cityoflearning.me/explore

**Comment by timothyfcook** [comment]
@cameronscott137 let me know if you need anything for this.  @MatthewVita did some good work that will help you easily pull in the `opportunity_instance` data.

**Comment by timothyfcook** [comment]
When writing the .css be sure to reference the global variables setup in #66 for all major color uses, etc. Also, as you work, think of what you can add to the platform variables file by asking the question: "If I was a new city and wanted to easily adapt the platform for my use, what design elements would I need to change?" ....basically any attribute that repeats and is specific to a local use or brand.

Probably leave a comment in the css wherever these are used and refer to the file where they are found.

**Comment by cameronscott137** [comment]
've attached a polished mockup of the layout that @timothyfcook, @cheleaserdner and I did last Friday: https://www.dropbox.com/s/u7mow1xhbwvu425/CaaC_Explore_04072015.pdf?dl=0

Intent is similar to: https://www.tumblr.com/explore/trending (except our layout will be fluid.)
Interaction is similar to: http://masonry.desandro.com/

Our goal here is to present a seemingly endless cascade of opportunities for users to explore. Couple of notes:
- If possible, I'd like to leverage an infinity scroll here to eliminate pagination.
- The button-based topic nav is still being worked out, but we will provide a UI for users to then filer upcoming events via topic.
- Since users could reasonable want to search from anywhere on the site, we've moved a basic search input to the navigation, and will provide a link to an advanced search page.
- The circular icons in the lower-right corner of each card are intended to be badges.
- This layout supports two additions to the opportunity data model: an event icon (the circular images), and a 160-character event excerpt to appear in search.

Any questions, concerns, or feedback, please let me know. I've run this by Justin, and it seems simple to implement. I'll be putting this to code tomorrow evening so that we have work to look at in-browser on Friday.

**Comment by timothyfcook** [comment]
I like the truncated `short_description` field and `event_logo` I'll add those to issue for #50 for @justinxreese to finish revising the data model.

**Comment by timothyfcook** [comment]
@cameronscott137 did you get @cheleaserdner on Github yet?

**Comment by chelseaerdner** [comment]
Hi @timothyfcook, I made an account as of yesterday. Still finding my way around but, I am here!

**Comment by timothyfcook** [comment]
awesome! Welcome aboard. I'll add you to the Github team officially.... nvm looks like Cameron did.

**Comment by timothyfcook** [comment]
@cameronscott137 need any help getting code ready for tomorrow? Do you need anything from @justinxreese ?

**Comment by cameronscott137** [comment]
@timothyfcook Negative. Thank you.

**Comment by MatthewVita** [comment]
@cameronscott137 looks good!

Note: lazy loading/infinite scroll is on my todo list: https://github.com/saxifrage/CaaC_Explore#todo

Do you do HTML/CSS (or any preprocessor alternatives) or do you want me to convert the PDF over? Will there be search filtering since you didn't include those controls in your design? (I mean, it makes life easier for me, but I'm more than willing to code the filtering stuff, lmk).

edit: words

**Comment by timothyfcook** [comment]
@cameronscott137 cool. are you going to point to the actual seed data from the API endpoints ( #62 ) or just code a mock-up view sans data?

**Comment by timothyfcook** [comment]
@cameronscott137 looks like @MatthewVita has all the Angular variables created. He's going to point them at the JSON endpoints for "real" data. Once you have those html/css files done, share them with him and he can add in the variables (or you could work with him on it).

Sounds like it will easiest (for now) to get a mockup of the site running in his Angular repo, then later we can work with @justinxreese to integrate the two repos and marry Angular/Rails.

**Comment by MatthewVita** [comment]
@timothyfcook I just realized I may be blocked because of https://github.com/saxifrage/learn/issues/86 :C

**Comment by timothyfcook** [comment]
Latest mockup: https://www.dropbox.com/s/fnloer57s1qtl6e/CaaC_Explore_04162015.pdf?dl=0

**Comment by timothyfcook** [comment]
You can do it! Remember:

![809494](https://cloud.githubusercontent.com/assets/1823300/7382518/e818db62-eddd-11e4-9952-3b68a8f92513.jpg)
