### ISSUE TITLE
Create Monomark for CaaC Brand

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#79]
For Chelsea when she on-boards.

**Comment by timothyfcook** [comment]
@chelseaerdner add the .pdf to this issue and as you share work with me do it here as well, rather than via e-mail.

Thanks! Good start on the logos.

**Comment by chelseaerdner** [comment]
Hi all, 

Below are the two CaaC brand options we reviewed today. The outcome of our conversation was to take the first option and step back from showcasing cities as a focal point of the brand and incorporate the idea of connections in a more technical way. Keep the same approach style-wise with the bold, circular monomark but explore a grid, interconnection layers, and bringing people together.

I welcome any further feedback, it is all very helpful in the process. I will continue to post iterations here next week as I begin to work through some of these things. 

![caac_brandoptions_styleresearch](https://cloud.githubusercontent.com/assets/11842603/7096989/d730f966-df9f-11e4-8616-1c58bf0ec7ce.png)

![caac_brandoptions_04102015_opt1](https://cloud.githubusercontent.com/assets/11842603/7097005/edc75bde-df9f-11e4-97e8-2a11dab71dda.png)

![caac_brandoptions_04102015_opt1_2](https://cloud.githubusercontent.com/assets/11842603/7097011/0010d5ea-dfa0-11e4-8960-14145f98adc8.png)

![caac_brandoptions_04102015_opt1_3](https://cloud.githubusercontent.com/assets/11842603/7097020/0eaa7eb2-dfa0-11e4-8119-a2e119e1cf2c.png)

![caac_brandoptions_04102015_opt2_1](https://cloud.githubusercontent.com/assets/11842603/7097041/24c235c8-dfa0-11e4-9987-5b7f9071fabd.png)

![caac_brandoptions_04102015_opt2_2](https://cloud.githubusercontent.com/assets/11842603/7097048/2fd0e8a6-dfa0-11e4-8383-ba24663e0148.png)

![caac_brandoptions_04102015_opt2_3](https://cloud.githubusercontent.com/assets/11842603/7097051/3924a29e-dfa0-11e4-8791-88381b774a66.png)

**Comment by MatthewVita** [comment]
WOW, Looks beautiful.

![](http://i.imgur.com/7drHiqr.gif)

**Comment by MatthewVita** [comment]
so I implemented my mocked up client with the new navbar search approach and added a skeleton to mimick the new design (I'll need the actual HTML/CSS when @cameronscott137  and @chelseaerdner get the chance, however):

![alt tag](http://i.imgur.com/zc8UIqu.png)

https://github.com/saxifrage/CaaC_Explore/commit/09edeaef6d8a4ccc440d07f416a229683b4f542e

**Comment by timothyfcook** [comment]
Nice. I think @cameronscott137 is coding it up, he just needs the JS/angular to put dynamic data into the HTML per #51

**Comment by MatthewVita** [comment]
## navbar:
- markup: https://github.com/saxifrage/CaaC_Explore/blob/master/app/shared/navbar/NavbarView.jade
- styles: https://github.com/saxifrage/CaaC_Explore/blob/master/app/shared/navbar/NavbarStyle.styl

## explore:
- markup: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/ExploreView.jade
- styles: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/ExploreStyle.styl

## explore cards:
- markup: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/cards/CardsView.jade
- styles: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/cards/CardsStyle.styl

## explore topics:
- markup: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/topics/TopicsView.jade
- styles: https://github.com/saxifrage/CaaC_Explore/blob/master/app/explore/topics/TopicsStyle.styl

## homepage:
- markup: https://github.com/saxifrage/CaaC_Explore/blob/master/app/home/HomeView.jade
- styles: (none at the moment)

@cameronscott137, you don't have to use Jade/Stylus... I just use them as my tools but am more than happy to swap them out to your preferences. You can start building up the styles/markup, but note that the Angular fields are still using silly test data. It's on my todo list to switch them to more meaningful fields (I've been focused on the functionality, not the usefulness of the data, of course), but it really shouldn't impede you (just use whatever classes you want and I'll work with those later on).

Also, note that lazy loading IS now implemented, but you won't see it because there's not enough test data. It works/shows the button if there's at least 20 items in the dataset. Since we're following City of Learning's `explore` feature, I used the "See More..." button to invoke loading... you can make that asset separately.

@timothyfcook what is the status of the JSON API endpoints? I would love to get away from my silly test data express server, but am not sure what you and Justin are up to (haven't been reading the issues as much as I should have this week). Also, did you hear from Justin about how he wants to move forward with integrating the Angular client with RoR? I have some ideas but will hold off since he's the RoR expert :+1:

**Comment by chelseaerdner** [comment]
Hi All, 

Attached is another rev of the logo for City as a Campus logo. We stepped back from the idea of including a city skyline in favor of a more technical approach that explores the idea of a grid, connections, and bringing people together. 

Our focal point is an aerial view of an interconnected grid that can represent a city, the quad of a campus, or even something closer to a circuit board. The mark works scaled at a larger size in which we can include as much detail as we'd like such as, street lines and textures, and it also works in a smaller scale where it takes on more of a technical look. The color palette a little brighter than I proposed before but is still representative of a campus scenery to tie in the concept of City as a Campus. Utilizing the idea of streets connecting with one another gives us the opportunity to play out patterns and textures that compliment the logo throughout the rest of the platform, if need be.

My preference is for the center version. It is bold, clean, and open. I think that it is strong enough to stand on it's own without a stroke around it. However, the stroke also adds to the badge effect if that is something we'd like to play up. 

As always, I welcome everyone's feedback!

![caac_brandoptions_04162015-01](https://cloud.githubusercontent.com/assets/11842603/7184999/46d2a1e2-e42e-11e4-8dec-4916667a7aa0.png)

**Comment by MatthewVita** [comment]
I'm voting for the one in the middle :+1:

**Comment by timothyfcook** [comment]
Agree on the middle one! :+1:

**Comment by timothyfcook** [comment]
Going to let @chelseaerdner close this issue!
