### ISSUE TITLE
Integrate Angular Data-Binding into Rails App

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#88]
In our final Explore page we want the content to load using angular data-binding that is pointed at our own API.

@MatthewVita has this up and working to some degree here: https://github.com/saxifrage/CaaC_Explore

but we should fold everything into one sweet Angular-on-Rails repo. In general, let's define how they work together in the MVC framework.

Just spitballing here, but seems like we can use Rails for the Model and Angular for the Controller/View?

**Comment by MatthewVita** [comment]
Often, MV\* clients (such as Angular) consume a backend API (RoR, .NET Web API, Flask, etc). It's just a separation of client and server, no need to limit RoR to just Models.

**Comment by MatthewVita** [comment]
where "API" === "RESTful JSON API", of course :)

**Comment by MatthewVita** [comment]
...going to follow some RoR + Angular tutorials to set up a barebones Docker container to try things out/see what works

**Comment by MatthewVita** [comment]
Okay, so I looked at some various ways to go about this and the way I like the most is by simply using RoR's `public` directory to serve the client app with this entry point:

https://github.com/saxifrage/CaaC_Explore/blob/master/app/index.html

Not sure how Heroku handles running hooks, but it would have to `cd` to the `public` directory and run `npm i && gulp production`, in order to compile everything into the `min.js` and `min.css` files. Also NGINX would have to make sure it serves up this directory when `/` requests are made, otherwise all of the other requests would be mapped to `/api/etc/etc/`

**Comment by timothyfcook** [comment]
We'll have to get @justinxreese to weigh in on his return from his music festival voyage. Integrating Angular/Rails into one repo is a major goal for the next week. That and the completion of populating Cameron's Explore and Opportunities page designs. Gonna be pretty!

**Comment by justinxreese** [comment]
I like putting the static site into the public directory. We can use codeship to build the app on deploys

**Comment by timothyfcook** [comment]
Excellent. Let's make it happen. Chad and I are in Chicago right now working on the sister City of Learning project.

**Comment by MatthewVita** [comment]
@justinxreese great! We're far off from worrying about provisioning, deploy hooks, and all that jazz, but at least we have a good strategy.

Closing for now.
